(() => {
  const token = new URLSearchParams(location.search).get('token');
  const stateKey = 'ridgeback-benchmark-configurator-v1';
  let caps, result, draft;
  const $ = id => document.getElementById(id);
  const api = async (path, body) => {
    const response = await fetch(path, {method: body ? 'POST' : 'GET', headers: {'X-Configurator-Token': token, ...(body ? {'Content-Type':'application/json'} : {})}, body: body ? JSON.stringify(body) : undefined});
    const value = await response.json();
    if (!response.ok) throw value;
    return value;
  };
  const save = () => localStorage.setItem(stateKey, JSON.stringify(draft));
  const profile = () => caps.profiles[draft.profile];
  const esc = value => String(value ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const active = record => !!record && ['running','cancelling'].includes(record.state);
  let runId = null, runTimer = null, currentRun = null;
  const field = (label, key, value, type='text') => `<label class="field">${label}<input data-top="${key}" type="${type}" value="${String(value ?? '').replaceAll('"','&quot;')}"></label>`;
  const visible = (axis, args) => {
    const axes = profile().variant_fields || [];
    const defaultFor = key => axes.find(item => item.key === key)?.default;
    const estimator = args.estimators ?? profile().fixed_arguments?.estimators ?? defaultFor('estimators');
    const recipe = args.isolation_2d ?? defaultFor('isolation_2d');
    return (!axis.estimators || axis.estimators.includes(estimator)) && (!axis.recipes || axis.recipes.includes(recipe));
  };
  function defaultDraft() { const d=caps.defaults; const first=caps.questions.find(x=>x.profile==='measurement'); return {question:first.id,profile:'measurement',inputs:{dataset:'',sensor_capture:'',mask_caches:[]},sweep_path:'',workers:d.workers,model_workers:d.model_workers,output_dir:'',baseline:'baseline',variants:[{name:'baseline',arguments:{}}],materializations:[{name:'candidate',mask_producer:'slimsam'}]}; }
  function boundary() { const p=profile(); $('boundary').innerHTML=`<p class="step">Evidence boundary</p><h2>${p.label}</h2><strong>Held constant</strong><ul>${(p.held_constant||[]).map(x=>`<li>${x}</li>`).join('')}</ul><strong>Rerun</strong><ul>${(p.rerun||[]).map(x=>`<li>${x}</li>`).join('')}</ul>${p.unavailable_reason?`<p class="issue">${p.unavailable_reason}</p>`:''}`; }
  function renderQuestions(){ $('questions').innerHTML=caps.questions.map(q=>{const p=caps.profiles[q.profile];return `<button class="question ${q.profile===draft.profile?'selected':''}" data-profile="${q.profile}" ${p.available?'':'disabled'}><span>${q.label}</span><small>${q.description}</small></button>`}).join(''); $('questions').querySelectorAll('button').forEach(b=>b.onclick=()=>{draft.profile=b.dataset.profile;draft.question=caps.questions.find(q=>q.profile===draft.profile).id;draft.variants=[{name:'baseline',arguments:{}}];draft.baseline='baseline';render();}); }
  function renderInputs(){ const kind=draft.profile; let content=''; if(kind==='measurement')content=`${field('Legacy measurement dataset', 'dataset',draft.inputs.dataset)}${field('Measurement workers', 'workers',draft.workers,'number')}`; else if(kind==='mask-output')content=`${field('Sensor capture', 'sensor_capture',draft.inputs.sensor_capture)}${field('Mask cache paths (comma separated)', 'mask_caches',(draft.inputs.mask_caches||[]).join(','))}${field('Measurement workers', 'workers',draft.workers,'number')}`; else if(kind==='mask-model')content=`${field('Sensor capture', 'sensor_capture',draft.inputs.sensor_capture)}${field('Measurement workers', 'workers',draft.workers,'number')}${field('Model workers', 'model_workers',draft.model_workers,'number')}`; else content=`${field('Existing live sweep YAML', 'sweep_path',draft.sweep_path)}<p class="muted">Live jobs reference an existing validated sweep rather than copying its process configuration.</p>`; content+=field('Output directory', 'output_dir',draft.output_dir); $('input-fields').innerHTML=content; if(kind==='mask-model'){const m=draft.materializations?.[0]||{name:'candidate',mask_producer:'slimsam'};const fields=profile().materialization_fields||[];$('input-fields').innerHTML+=`<div class="variant"><p class="step">Mask materialization</p><div class="variant-fields"><label class="field">Name<input data-materialization="name" value="${m.name}"></label>${fields.map(x=>inputFor(x,m[x.key]??x.default,'materialization')).join('')}</div></div>`;} document.querySelectorAll('[data-top]').forEach(i=>i.oninput=()=>{const key=i.dataset.top;if(['dataset','sensor_capture'].includes(key))draft.inputs[key]=i.value;else if(key==='mask_caches')draft.inputs.mask_caches=i.value.split(',').map(x=>x.trim()).filter(Boolean);else draft[key]=i.value;save();validate();});document.querySelectorAll('[data-materialization]').forEach(i=>i.oninput=()=>{const m=draft.materializations?.[0]||{};m[i.dataset.materialization]=i.value;draft.materializations=[m];save();validate();}); }
  function inputFor(axis,value,index){ const data=index==='materialization'?`data-materialization="${axis.key}"`:`data-axis="${axis.key}" data-index="${index}"`;const choices=axis.type==='select'?`<select ${data}>${axis.options.map(x=>`<option ${String(value)===String(x)?'selected':''}>${x}</option>`).join('')}</select>`:`<input ${data} type="${axis.type==='text'?'text':'number'}" value="${value}" min="${axis.min??''}" max="${axis.max??''}" step="${axis.step??'any'}">`;return `<label class="field">${axis.label}${choices}</label>`; }
  function renderVariants(){ const p=profile(); const live=draft.profile==='live-system'; $('add-variant').disabled=live||!p.available;if(live){$('variants').innerHTML='<p class="muted">The referenced live sweep is the canonical configuration for this job.</p>';return;}$('variants').innerHTML=draft.variants.map((variant,index)=>{const args=variant.arguments;return `<article class="variant"><div class="variant-head"><input data-name="${index}" aria-label="Variant name" value="${variant.name}"><label class="field">Baseline<select data-baseline="${index}">${draft.variants.map(item=>`<option ${draft.baseline===item.name?'selected':''}>${item.name}</option>`).join('')}</select></label>${draft.variants.length>1?`<button class="secondary" data-remove="${index}">Remove</button>`:''}</div><div class="variant-fields">${p.variant_fields.filter(x=>visible(x,args)).map(x=>inputFor(x,args[x.key]??x.default,index)).join('')}</div></article>`;}).join(''); document.querySelectorAll('[data-axis]').forEach(i=>i.oninput=()=>{const v=draft.variants[+i.dataset.index];v.arguments[i.dataset.axis]=i.value;renderVariants();save();validate();});document.querySelectorAll('[data-name]').forEach(i=>i.oninput=()=>{const v=draft.variants[+i.dataset.name];if(draft.baseline===v.name)draft.baseline=i.value;v.name=i.value;save();validate();});document.querySelectorAll('[data-baseline]').forEach(i=>i.oninput=()=>{draft.baseline=i.value;save();validate();});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{draft.variants.splice(+b.dataset.remove,1);draft.baseline=draft.variants[0].name;render();}); }
  function estimates(data){ const e=data.estimates||{};const cells=[['Trials',e.trials??'Unknown'],['Events',e.events??'Unknown'],['Measurement work',e.measurement_work??'Unknown'],['Capture',e.capture_duration??'Unknown'],['Hard limit',e.hard_timeout??'Unknown']]; $('estimates').innerHTML=cells.map(([a,b])=>`<div class="estimate"><small>${a}</small><strong>${b}</strong></div>`).join('')+(e.assumptions||[]).map(x=>`<p class="muted">${x}</p>`).join(''); }
  function issues(data){ $('issues').innerHTML=(data.issues||[]).map(x=>`<div class="issue">${x.message}</div>`).join('')+(data.valid?'<div class="issue notice">Validated by the same replay-job contract used by the CLI.</div>':''); }
  async function validate(){ try{result=await api('/api/validate',{job:draft});issues(result);estimates(result);$('command').textContent=result.valid?'Ready to render the exact command.':'Resolve the listed issue(s) first.';}catch(e){issues({issues:e.issues||[{message:e.error||'Service unavailable.'}]});} }
  async function inspect(){try{const path=draft.profile==='measurement'?draft.inputs.dataset:draft.inputs.sensor_capture;const x=await api('/api/inspect',{path});$('artifact-summary').textContent=x.issues?.length?x.issues[0]:`${x.kind}: ${x.trials} trials, ${x.events} events`;validate();}catch(e){$('artifact-summary').textContent=e.issues?.[0]?.message||'Could not inspect evidence.';}}
  // The server stamps times as "%Y-%m-%d %H:%M:%S %z", which Date cannot read
  // until the offset is separated by a colon.
  const stamp = value => {const parsed=new Date(String(value??'').replace(' ','T').replace(' ','').replace(/([+-]\d{2})(\d{2})$/,'$1:$2'));return isNaN(parsed)?null:parsed;};
  function elapsed(record){const from=stamp(record.started),to=record.finished?stamp(record.finished):new Date();if(!from||!to)return 'Unknown';const total=Math.max(0,Math.round((to-from)/1000)),hours=Math.floor(total/3600),minutes=Math.floor(total%3600/60);return (hours?`${hours}h ${minutes}m `:minutes?`${minutes}m `:'')+`${total%60}s`;}
  function runAvailability(){const live=draft.profile==='live-system';$('start').disabled=live||active(currentRun);$('start-note').textContent=live?'A live sweep still starts from a terminal: it needs a GPU-backed X session, and its preflight cleanup would kill this page. Copy the command and run it there.':'';}
  function renderRun(record){currentRun=record;if(!record){$('run-status').innerHTML='';$('run-log').textContent='No run started from this page yet.';$('cancel').disabled=true;runAvailability();return;}$('cancel').disabled=!active(record);$('run-status').innerHTML=[['State',record.state],['Elapsed',elapsed(record)],['Exit code',record.returncode??(active(record)?'Still running':'None recorded')],['Profile',record.profile],['Output',record.output_dir]].map(([label,value])=>`<div class="estimate"><small>${label}</small><strong>${esc(value)}</strong></div>`).join('');$('run-log').textContent=record.log||record.command||'';runAvailability();}
  async function pollRun(){if(!runId)return;try{const wasActive=active(currentRun),record=await api(`/api/runs/${runId}`);renderRun(record);if(active(record)){runTimer=setTimeout(pollRun,1500);return;}runTimer=null;if(wasActive)await loadResults();}catch(e){runTimer=null;}}
  // A record from /api/runs carries no log, so re-attaching always asks for the
  // detail once even when the run is already over.
  function attach(record){if(runTimer){clearTimeout(runTimer);runTimer=null;}runId=record?record.run_id:null;renderRun(record);if(record)pollRun();}
  async function startRun(){try{const data=await api('/api/run',{job:draft});issues(data);estimates(data);if(!data.run)return;$('command').textContent=data.run.command;attach({...data.run,log:''});}catch(e){issues({issues:e.issues||[{message:'Could not start the run.'}]});}}
  async function cancelRun(){if(!runId)return;try{renderRun(await api(`/api/runs/${runId}/cancel`,{}));}catch(e){issues({issues:e.issues||[{message:'Could not cancel the run.'}]});}if(!runTimer)runTimer=setTimeout(pollRun,600);}
  const resultDetail = entry => Object.entries(entry.summary||{}).filter(([,value])=>value!==null&&value!==undefined&&value!=='').map(([key,value])=>`${key.replaceAll('_',' ')}: ${Array.isArray(value)?value.join(', '):value}`).join(' · ');
  function renderResults(list){if(!list.length){$('results').innerHTML='<p class="muted">Nothing under artifacts/benchmarks yet.</p>';return;}$('results').innerHTML=list.map((entry,index)=>{const rename=entry.rename||{};return `<article class="result"><div><p class="result-head"><strong>${esc(entry.name)}</strong><span class="tag">${esc(entry.kind)}</span></p><p class="muted">${esc(resultDetail(entry)||entry.path)}</p>${rename.warning?`<p class="issue">${esc(rename.warning)}</p>`:''}${rename.note?`<p class="muted">${esc(rename.note)}</p>`:''}${rename.reason?`<p class="muted">Rename refused: ${esc(rename.reason)}</p>`:''}</div><button class="secondary" data-rename="${index}" ${rename.allowed?'':'disabled'}>Rename</button></article>`;}).join('');document.querySelectorAll('[data-rename]').forEach(button=>button.onclick=()=>renameResult(list[+button.dataset.rename]));}
  async function loadResults(){try{renderResults((await api('/api/results')).results);}catch(e){$('results').innerHTML='<p class="muted">Could not list results.</p>';}}
  async function renameResult(entry){const name=prompt(`New name for ${entry.name}`,entry.name);if(!name||name===entry.name)return;try{await api('/api/results/rename',{path:entry.path,name});await loadResults();}catch(e){issues({issues:e.issues||[{message:'Could not rename that directory.'}]});}}
  async function render(){renderQuestions();boundary();renderInputs();renderVariants();runAvailability();save();await validate();}
  async function exportJob(){try{const data=await api('/api/render',{job:draft});result=data;issues(data);estimates(data);if(!data.valid)return;$('command').textContent=data.command;const blob=new Blob([data.yaml],{type:'text/yaml'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=data.filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);}catch(e){issues({issues:e.issues||[{message:'Could not render job.'}]});}}
  async function init(){try{caps=await api('/api/capabilities');draft=JSON.parse(localStorage.getItem(stateKey)||'null')||defaultDraft();if(!caps.profiles[draft.profile]?.available)draft=defaultDraft();await render();$('inspect').onclick=inspect;$('add-variant').onclick=()=>{draft.variants.push({name:`variant_${draft.variants.length+1}`,arguments:{}});render();};$('download').onclick=exportJob;$('copy').onclick=async()=>{const data=await api('/api/render',{job:draft});if(data.valid){$('command').textContent=data.command;await navigator.clipboard.writeText(data.command);}};$('reset').onclick=()=>{draft=defaultDraft();render();};$('start').onclick=startRun;$('cancel').onclick=cancelRun;$('refresh-results').onclick=loadResults;
      // The tab is a viewer, never the owner: whatever the server already knows
      // about is picked back up here, including a run started before this load.
      attach((await api('/api/runs')).runs[0]||null);await loadResults();$('import').onchange=async e=>{const text=await e.target.files[0].text();try{const data=await api('/api/import',{yaml:text});draft=data.job;render();}catch(err){issues({issues:err.issues||[{message:'Could not import job.'}]});}};}catch(e){document.body.innerHTML='<main class="workspace"><h1>Configurator unavailable</h1><p>Restart the local service and open the printed URL.</p></main>';}}
  init();
})();
